-- ************************ SCRIPT DE BORRADOS DE TABLA  ************************
/*DROP TABLE TBCORREOSSEDE;
DROP TABLE TBCORREOSUSUARIOS;
DROP TABLE TBDONACION;
DROP TABLE TB_TIPODONACION;
DROP TABLE TBTELEFONOSUSUARIOS;
DROP TABLE TBTELEFONOSSEDES;
DROP TABLE TBUSUARIOS;
DROP TABLE TBROL;
DROP TABLE TBSEDE;
DROP TABLE TBLOCALIZACION;*/